name: Build and Deploy to Firebase Functions
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Decode GCP_SA_KEY
        run: echo ${{ secrets.GCP_SA_KEY }} | sed 's/\\n/\n/g' > /tmp/gcp_key.json
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy functions
        env:
          GCP_SA_KEY: /tmp/gcp_key.json